spring:
  application:
    name: todo_practice
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    hidden method:
      filter:
        enabled: false